### PR TITLE
fix: views count undefined

### PR DESCRIPTION
**Pull request by gustavobonassa**
Sometimes I find a live with 0 viewers, and it crashes my server
Screenshot_8
Screenshot_1

### CODE REVIEW

**Comment by talmobi** [comment]
published patch `yt-search@2.1.10`

That's a live stream showing up as a video result?

**Comment by gustavobonassa** [comment]
Yes, the lives are coming together with the videos :/

**Comment by talmobi** [comment]
Yes. Publishing another temp fix that crashes when countering live (similar to this fix). `yt-search@2.1.11`

Will make addition to rid those live streams away from videos and into its own category tomorrow.

Thanks for this~

**Comment by talmobi** [comment]
@gustavobonassa consider updating to `yt-search@2.2.0` as it prevents live streams from showing up in video results and instead puts them into their own `result.live` array.

**Comment by gustavobonassa** [comment]
Ok, thks

**Pull request merged**
